### ISSUE TITLE
Value of default_reg_path?

### ISSUE THREAD

**Issue by Harm10** [jiri-otoupal/pycrosskit#1] opened 2021-05-02 16:40 UTC
I tried this package and when within python console I get an error that default_reg_path is not defined on the get_var example.
I am on Win 10.
Should the example be updated to make it work?

The examples should at least be extended with this line of code:
`from pycrosskit.envariables import SysEnv`

**Comment by jiri-otoupal** [comment] 2021-05-02 17:19
I will take a look and fix it today or tommorow 👍 
Thanks for reporting a issue

**Comment by jiri-otoupal** [comment] 2021-05-02 17:30
Can you please provide me with version that you are using or code ? 
I can not reproduce the error.

**Comment by Harm10** [comment] 2021-05-03 22:30
pycrosskit 1.0.3.3 on Python 3.7.9 with testing code in Python console:
`from pycrosskit.envariables import SysEnv`
`SysEnv.get_var('RIDETEST', reg_path=default_reg_path, delete=False)`

I get 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'default_reg_path' is not defined

**Comment by jiri-otoupal** [comment] 2021-05-03 23:24
Should be fixed now in version 1.0.3.4, please check it

**Comment by Harm10** [comment] 2021-05-04 06:12
Sorry but no. Updated and ran same code with same response.

**Comment by jiri-otoupal** [comment] 2021-05-04 10:36
Currently there is no code containing default_reg_path.
Please check if python that you are running it with has the new version.
Also i see that your code that you sent contains `default_reg_path`
Please replace your code with:
`SysEnv.get_var('RIDETEST', delete=False)`

**Comment by Harm10** [comment] 2021-05-04 17:12
I followed your example............. :-)

But when I do the last suggestion I get another error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Program Files\Python\lib\site-packages\pycrosskit\envariables.py", line 23, in get_var
    value = winreg.QueryValue(policy_key, name)
FileNotFoundError: [WinError 2] Het systeem kan het opgegeven bestand niet vinden`

**Comment by jiri-otoupal** [comment] 2021-05-05 13:11
It looks like that the registry path does not exists on your system,
now it should write it instead of exception

**Comment by Harm10** [comment] 2021-05-05 20:00
Where should this reg key be located in the registry?
I have Windows 10.

**Comment by jiri-otoupal** [comment] 2021-05-05 21:54
Registry can have many "directories" check your regedit ( Type regedit to start menu ). Choose path where you want to save the variable it can look like this "Computer\HKEY_CURRENT_USER"

**Comment by Harm10** [comment] 2021-05-06 09:40
So you want me to add something? And what should the value of the key be? And this is not in your installation description? Shouldn't the installation of the package take care of this?

**Comment by jiri-otoupal** [comment] 2021-05-06 21:06
You dont have to add anything, your registry just does not have default path like that.

In example try to pass "Computer\HKEY_LOCAL_MACHINE" to reg_path

SysEnv.get_var('RIDETEST', reg_path="Computer\HKEY_LOCAL_MACHINE", delete=False)

**Comment by Harm10** [comment] 2021-05-07 15:14
I upgraded the package to 1.0.4.1 and after executing your last command I get error:
`Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pycrosskit.envariables import SysEnv
>>> SysEnv.set_var("test", "test", registry=False)

SUCCESS: Specified value was saved.
>>> SysEnv.get_var("test", delete=False)
This Registry Path does not exists on this system
Please check path in regedit.exe`

**Comment by Harm10** [comment] 2021-05-07 16:31
I ran the get_var with your addition and it executes fine.

I assume I will not get a write to console for that SUCCESS message if I execute the set_var in a python script?
Perhaps you can add some message=False option to that command?

So I guess my problem is solved? But you need to update your documentation on GitHub................. :-)

**Comment by jiri-otoupal** [comment] 2021-05-08 14:16
Sure i will look on it, hope the work will go smoothly :)

**Closed by jiri-otoupal** 2021-05-08 14:16 UTC
